apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-yp45
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-bnyw-tenant/rhtap-demo-app/hacbs-test-project-yp45@sha256:bdea558f0ac49fa0c82d8619c8368e8ede7e196a96c6e71cde54efdff2065b4a
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
