apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-yp45
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-yp45
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-yp45
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-yp45
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-yp45
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-bnyw-tenant/rhtap-demo-app/hacbs-test-project-yp45@sha256:bdea558f0ac49fa0c82d8619c8368e8ede7e196a96c6e71cde54efdff2065b4a
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
